definitions:
  models.Error:
    properties:
      message:
        type: string
    type: object
  models.Message:
    properties:
      priority:
        type: string
      text:
        type: string
    type: object
  models.StandardErrorModel:
    properties:
      error:
        $ref: '#/definitions/models.Error'
    type: object
info:
  contact: {}
paths:
  /v1/:
    get:
      consumes:
      - application/json
      description: This API for getting message
      parameters:
      - description: messageGetRequest
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.Message'
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
      summary: GetMessage
      tags:
      - message
swagger: "2.0"
